name: CI - Dev pipeline

on:
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Lint backend
        working-directory: backend
        run: npm run lint

      - name: Audit backend
        working-directory: backend
        run: npm audit --audit-level=high || true

      - name: Test backend
        working-directory: backend
        run: npm test

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint

      - name: Audit frontend
        working-directory: frontend
        run: npm audit --audit-level=high || true

      - name: Test frontend
        working-directory: frontend
        run: npm test

      - name: Build Docker images
        run: docker-compose build

