name: CD - Main deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env for backend
        run: echo "ENV=production" > backend/.env

      - name: Create .env for frontend
        run: echo "ENV=production" > frontend/.env

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:backend ./backend

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:frontend ./frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:backend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:frontend

